apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-pod
    type: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # 30000 - 32767