apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: vote-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      name: postgres
      app: vote-ms
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
        app: vote-ms
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: db # host name for service
  labels:
    name: postgres-service
    app: vote-ms
spec:
  type: NodePort
  selector:
    name: postgres
    app: vote-ms
  ports:
  - port: 5432
    targetPort: 5432

