apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: vote-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis
      app: vote-ms
  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: vote-ms
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: vote-ms
spec:
  type: NodePort
  selector:
    name: redis
    app: vote-ms
  ports:
  - port: 6379
    targetPort: 6379
