apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: vote-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-pod
      app: vote-ms
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: vote-ms
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: vote-ms
spec:
  type: LoadBalancer
  selector:
    name: voting-app-pod
    app: vote-ms
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

