apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: vote-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-app-pod
      app: vote-ms
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: vote-ms
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1